### ISSUE TITLE
Allow retries in LMS without swamping the logs

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1080]
**Background**

As a consequence of metrics requirements we have to implement an `upsert` style query. In order to support this quickly (as updating Postgres to 9.5 to support "INSERT ... ON CONFLICT" isn't on the cards right now), this is going to be implemented with a retry on conflict mechanism in the code using `pyramid_retry`.

The consequence of this is the without special handling the retried elements will be logged as errors even if the eventual retried request works fine. 

**Desired outcome**

 * We can implement `pyramid_retry` without having repeated log messages on retried items

**Solution**

 * Use `h-pyramid-sentry` which packages this behavior in LRS

**Acceptance critera**

 * [x] `h-pyramid-sentry` no longer forces the consumer to depend on `pyramid_retry` and `celery` if they are not required
   * [ ] Update `h` to be compatible with the change
 * [x] `h-pyramid-sentry` has been integrated into LMS
 * [x] Any tests or code relating to Sentry SDK in LMS have been removed
* [ ] `Event` in h-pyramid-sentry should be public

**Comment by jon-betts** [comment]
@seanh has started a merge request with this and some more in: https://github.com/hypothesis/lms/pull/1074

Do we want to scope that down to just this? Or increase the scope of this ticket to include the retry mechanism? Seems like we might as otherwise this can't easily be tested.

**Comment by seanh** [comment]
Let's scope this just to moving LMS to h-pyramid-sentry, which will mean that LMS inherits proper handling of Sentry crash reporting when pyramid_retry and pyramid_exclog are involved.

I'll then add retrying of requests the fail with IntegrityErrors to LMS, as a separate issue.

Note that Postgres 9.5's `INSERT ... ON CONFLICT` *would not* fix these issues in the general case. I believe it only fixes concurrency issues in the specific case of when upserting by primary key. The more general case here is:

An error (such as a sqlalchemy `IntegrityError`, but it could be any kind of error) is raised because of some sort of "transient" condition (for example a concurrent requests race condition created by upsert or create-if-not-exists logic, but it could be any kind of transient condition).

With pyramid_retry you can mark the error in question as retryable then the request can be retried up to 2 times. This is a general solution to "transient" or "retryable" errors that also happens to cover the specific case of upserting a single DB row.

**Comment by jon-betts** [comment]
Yep, not a general fix, but if the intent was to get the metrics thing done as quickly as possible, it might have done the job.

There's a merge request with the dependency drop in `h-pyramid-sentry` now so it doesn't force you to load celery:

 * https://github.com/hypothesis/h-pyramid-sentry/pull/11

**Comment by seanh** [comment]
Added an item to the task list above: `Event` in h-pyramid-sentry should be public
