### ISSUE TITLE
Need to handle exceptions on the UI

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1240]
Currently we don't have a way to handle errors in the UI that arise from exceptions from service requests. The errors need to inform users that something bad has happened so that they know the state of the application is broken or failed and they may be able to relay that error back to the support team easily.

The client sidebar uses a small toast notification that hides after a few seconds. We could implement something similar to this

![Screen Shot 2019-12-04 at 11 01 15 AM](https://user-images.githubusercontent.com/3939074/70172403-72296b80-1685-11ea-9b24-c0a553aff06c.png)

Its also worth exploring error boundaries in our components as a way to better handle exceptions
https://reactjs.org/docs/error-boundaries.html
Does this have support in preact?

**Comment by robertknight** [comment]
> Currently we don't have a way to handle errors in the UI that arise from exceptions from service requests.

We do have error handling for various requests that are triggered from UI components (eg. from effects). What I think this issue was about was error handling for requests that are triggered outside of UI components, eg. in response to RPC messages from the Hypothesis client.

Since the scope was a little unclear here I'm going to close this. When we have some specific examples of errors that are not handled that we need to deal with, we can file an issue for that.
