### ISSUE TITLE
Investigate Google Picker permissions to see if we can reduce the permissions needed

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#1333]
Our current GDrive permissions to enable use of the Google Picker are: "See, edit, create, and delete all of your Google Drive files".

Jon says:

> This is Google's Drive Picker sample.
> https://appmaker.google.com/edit/1_M_GrYRJt3jssrNXpxtRdDw1jXkGftqF?authuser=0#Pages/DrivePickerSample/component=DrivePickerSample
> It only asks for read and download permission.

> We are using GOOGLE_DRIVE_SCOPE = 'https://www.googleapis.com/auth/drive'
> (https://github.com/hypothesis/lms/blob/6387faa3936efb2f4ba3cfe79c1a301218190d55/lms/static/scripts/frontend_apps/utils/google-picker-client.js#L3)
> I wonder if we could instead use:
> GOOGLE_DRIVE_SCOPE = 'https://www.googleapis.com/auth/drive.file'
> https://developers.google.com/drive/api/v2/about-auth (edited) 

Robert says:

> This looks like something we might be able to change quite easily. At a minimum we could change the last part of the scope to drive.readonly.

**Comment by klemay** [comment]
My only concern here is that we don't want to take away the ability to upload files using our picker - if we move to a read-only model, will that get taken away?

**Comment by klemay** [comment]
Also, I'd be remiss not to link https://github.com/hypothesis/lms/issues/928 to any discussion of changing how Google picker permissions work :)

**Comment by mkdir-washington-edu** [comment]
Robert added:

> We currently use non-read only permissions so that we can change the sharing settings on the file, in order to make it viewable through Via.
> 
> We’d need to change how that works first.
> 
> This makes this more complex than I thought.

**Comment by mkdir-washington-edu** [comment]
Two questions to consider when looking at the current permissions:
1) Can users within an organization find files set to "Anyone can view"?
- Jeremy and I did some testing, and the answer seems to be "no". When Hypothesis changes the permissions of a PDF in Drive to "Anyone can view", it does not make the file searchable within the org's Drive.

2) Can people find the file outside the org?
With 32 characters in the unique URL, the answer would be "no".

**Comment by robertknight** [comment]
This came up again recently because Google introduced additional verification for OAuth clients using [Restricted Scopes](https://support.google.com/cloud/answer/13464325?hl=en&ref_topic=13460882&sjid=3789509495475849997-EU#) which includes `https://www.googleapis.com/auth/drive` and `https://www.googleapis.com/auth/drive.readonly`.

Relevant Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1718176476315619

The API that the frontend uses to change a file's sharing permission is [`permissions.create`](https://developers.google.com/drive/api/reference/rest/v3/permissions/create). According to these docs, it requires EITHER of these scopes:

- https://www.googleapis.com/auth/drive
- https://www.googleapis.com/auth/drive.file

The `drive.file` scope is not restricted as it is limited to specific files shared with an app, per https://developers.google.com/identity/protocols/oauth2/scopes.
