### ISSUE TITLE
Grading bar lists students in non-alphabetical order

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#1629]
When instructors have a grading bar in an LMS assignment, the student drop down lists student names an order that is not alphabetical. Based on a (dimly remembered) conversation in stand up, this is likely because we're getting passed the full name as a single string, and we're not dividing it. Since we don't want to order by first name, we're not ordering it, either, and the present order may be the result of which students enter the assignment first.

https://hypothesis.zendesk.com/agent/tickets/8559

Expected behavior:
Ideally, listing student names as "Last, First" in alpha order. Less ideally, keeping names as is but listing them in alpha order by last name.

![image](https://user-images.githubusercontent.com/22603275/78702692-ff502b80-78d6-11ea-99bb-5050d33edae4.png)

**Comment by LMS007** [comment]
We decided to forgo attempting to sort by last name because we don't have that granularity with the displayName and we would have to make too many assumptions about name(s) -- may of which could be wrong in a number of cases.

The first pass will be a simple sort on displayName --in most cases that will mean first name first. If we need to improve this, then we'll need to consider requiring more data about the last name in the db.

https://github.com/hypothesis/lms/issues/1629
