### ISSUE TITLE
Fix and re-enable feature flags cookie

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1693]
I'm not sure what exactly was broken, but the feature flags cookie was disabled by https://github.com/hypothesis/lms/pull/1571 because it wasn't working. Re-enable it and fix whatever's wrong with it.

Related: _Feature flags cookie settings need to be tri-state not two-state_ https://github.com/hypothesis/lms/issues/790

**Comment by jon-betts** [comment]
This is kind of an awkward state. The linked PR re-enables the cookie feature flags, and fixes them (hopefully) in QA and prod, but they don't work locally. 

This is because we:

 * Must enable secure cookies to get them in an iframe (like we are in LMS)
 * But don't run behind SSL in dev, so they get disabled again

We can re-configure dev to work in SSL by default. Not 100% on what's required there. It looks like `pserve` can't do it by default, but `gunicorn` can. I think there's a PR gone through to make `gunicorn` the default for LMS again: https://github.com/hypothesis/lms/pull/1743. So that's pretty convenient if true. We'd need a cert, and I'd need to know all the places that are expecting us to be be http, rather than https.

We can create a self signed certificate with following the instructions at: https://letsencrypt.org/docs/certificates-for-localhost/
