### ISSUE TITLE
Screen "flicker" when closing authorization popup window

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1826]
I don't think this used to happen: when I close the authorization popup window you can see that the entire iframe flashes (would be the entire browser tab if the assignment were configured to open in a new tab):

![Peek 2020-06-09 14-51](https://user-images.githubusercontent.com/22498/84155844-b9dbe600-aa60-11ea-83fe-afc050c67ef5.gif)

**Comment by robertknight** [comment]
There is an open PR in https://github.com/hypothesis/lms/pull/1844 but it is awaiting re-review from me.

**Comment by robertknight** [comment]
https://github.com/hypothesis/lms/pull/1844 resolved the flicker, however there is an issue that after the authorization popup is completed, the "Authorize Hypothesis" dialog briefly remains visible until both the groups and content are fetched, but there is no clear indication that anything is happening:

![Transition after authorizing](https://user-images.githubusercontent.com/2458/90742127-46a7e900-e2c7-11ea-8b25-918950d789be.gif)

The "Authorize" button in the dialog gets disabled while the iframe content URL is fetched after OAuth authorization completes, but not while the groups are being fetched. This means that if the content URL is already available or is fetched more quickly than the groups then the "Authorize" button remains enabled.

The issue in the code is to do with a difference between the `fetchGroups` and `fetchContentUrl` functions in `BasicLtiLaunchApp`. The `fetchContentUrl` unconditionally updates a counter of "API requests that block display of the content" (the `fetchContent` state) whereas `fetchGroups` does not, because whether fetching groups blocks display of the content depends on whether it happens on the initial launch (where it does not) or afterwards (where it does).
