### ISSUE TITLE
Polish design of "No files" state for Canvas/Blackboard file picker

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2192]
https://github.com/hypothesis/lms/pull/2146 introduced an initial solution for https://github.com/hypothesis/lms/issues/765 by adding an empty state to the LMS file picker dialog telling the user what has happened and what to do if there are no files in the current course.

Following the initial deployment there was some discussion over the design and proposals for improvements: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1603366119122900.

In particular it was suggested:

- The table doesn't look very table-like in the empty state because it is only one row high
- It would look better if the entire empty-state message were contained inside the table and centered
- There should be an affordance that allows the user to reload the file list without having to close and re-open the dialog

**Comment by seanh** [comment]
These are very rough but here are a couple of suggestions.

Basic dialog with <kbd>Try again</kbd> button:

![Screenshot from 2020-10-22 12-44-04](https://user-images.githubusercontent.com/22498/96880160-c3487680-1474-11eb-89ef-aed954ef0b44.png)

Note the language could be tighter. It should read _There are no PDFs in the course. See the help article..._. (Remove available, current, please and Canvas)

Empty-table design with the whole text message inside the table and centred, the table header gone when the table is empty, and a reload button:

![Screenshot from 2020-10-22 14-41-28](https://user-images.githubusercontent.com/22498/96880302-effc8e00-1474-11eb-961d-5ac050156410.png)

In either case I think that when the <kbd>Try again</kbd> or <kbd>Reload</kbd> button is clicked the "error message" needs to be replaced with a spinner for a couple of seconds before displaying the error message again (if there are still no files) because the user needs time to see that it did in fact reload even though there are still no results to display.

**Comment by seanh** [comment]
Instead of:

> See the help article for [uploading files to a course](example.com) and try again.

Maybe simplify it to:

> Try [adding files to the course](example.com) and reloading.

More direct and removes the techno term "upload".

So the whole thing would be:

> There are no PDFs in the course. Try [adding files to the course](example.com) and reloading.
>
> <kbd>Reload</kbd>

**Comment by seanh** [comment]
Suggestion:

![Screenshot from 2020-10-26 10-28-25](https://user-images.githubusercontent.com/22498/97161846-3fdd9c80-1776-11eb-915e-2b1303fc5e89.png)


Notes:

* The table maintains its full height when empty
* The entire "error message" is inside the table
* The message is horizontally and vertically centred within the table
* I've tightened up the text of the message:
  * Just "PDFs" not "available PDF files"
  * Just "the course" not "the current course"
  * Don't say "please"
  * Don't say "see the Canvas help article" (the **Add some files to the course** link should be a link to the Canvas help article)
* The table's column headers aren't shown when the table is empty, since the columns they refer to aren't present
* The <kbd>Try again</kbd> button is in its usual location in the bottom-right. Its label matches with the text in the middle, which tells the user to upload some files _and try again_.
* When you click the <kbd>Try again</kbd> button, if the empty files dialog / error message is going to be re-displayed because there still aren't any files, the UI needs to make a show of "trying" for some noticeable amount of time (a second or two) even if the network request actually comes back much quicker. It should replace the text in the middle of the files list with a spinner for one or two seconds. The spinner should be horizontally and vertically centred like the text is
