### ISSUE TITLE
DESIGN: UI for enabling Canvas groups and choosing the group set for an assignment

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2523]
This will happen when teachers are selecting the document source + document for their LMS assignment. See our [KB article outlining the assignment creation process](https://web.hypothes.is/help/using-the-hypothesis-app-with-assignments-in-canvas/) to get a sense of where in the overall flow this happens. We're talking about adding UI elements to Step 2 of that process, which looks like this:

![image](https://user-images.githubusercontent.com/12087705/112880406-6478d000-9098-11eb-825e-b52d491599dd.png)

We might consider turning this modal into a "wizard" where Step 1 is choosing document source, Step 2 is choosing document, and Step 3 is choosing whether to make this a group assignment + presenting a list of group sets to the instructor.

**Comment by klemay** [comment]
In case this is helpful, here is the UI Canvas provides for regular assignments (not available with External Tools, which is why we're building our own mechanism):

1. Check the box for "This is a Group Assignment"
<img width="489" alt="Screen Shot 2021-03-29 at 2 15 22 PM" src="https://user-images.githubusercontent.com/12087705/112881071-3ba50a80-9099-11eb-891c-15c1c383a8e6.png">

2.Choose a group set from the dropdown
<img width="456" alt="Screen Shot 2021-03-29 at 2 16 13 PM" src="https://user-images.githubusercontent.com/12087705/112881167-5bd4c980-9099-11eb-93bf-aa0a0c969cc6.png">

<img width="467" alt="Screen Shot 2021-03-29 at 2 16 34 PM" src="https://user-images.githubusercontent.com/12087705/112881204-63946e00-9099-11eb-853b-e847aa577af8.png">
(group sets are listed alphabetically with the first-alphabetically group selected by default)

3. Continue adding details like due date, instructions, etc.

Notes:
- In the Canvas UI for creating groups, a set of groups is called a Group Set. In the UI for assigning things to groups, they use a mix of Group Set and Group Category. Both terms mean the same thing. 
- I'm including this just to show the dropdown populated with Group Sets listed alphabetically, with one automatically selected. We are not giving the option to assign 1 grade to the whole group vs individually, nor providing an affordance to create new group sets from this screen (at least not for now!)
- This is not to say we must copy what Canvas is done; this is just what instructors see in other parts of Canvas and the sort of interaction they'll be expecting as a result.

**Comment by seanh** [comment]
I think copying the Canvas UI above is a good idea. Users will be used to using this API to create group assignments. So it'll be good if the UI for creating _Hypothesis_ group assignments is familiar. Of course we won't have the <samp>Assign Grades to Each Student Individually</samp> checkbox or the <kbd>New Group Category</kbd> button. But otherwise I think we could copy their design and wording as the basis for our own dialog

**Comment by seanh** [comment]
Although I notice that Canvas's UI refers to them as both "group sets" and "group categories" within the same dialog :)

**Comment by lyzadanger** [comment]
There was a discussion with the team on April 15, 2021, and a general consensus was gained for the high-level UI approach outlined here.

These wireframes pertain to the portion of assignment creation (or editing) that happen within the “configure external tool” (Hypothesis) steps of the process. The dialogs below are rendered by the LMS itself, in this case Canvas. We are able to control what shows up inside of these dialogs, but not the “chrome” of the dialogs (title, close X) nor anything outside of the dialog.

The initial dialog of the external-tool configuration will appear nearly identical to how it appears now: it will initially prompt the configuring user to select the source of the assignment content. Clicking/tapping a button here will pop up a smaller dialog (as it does today) to enter a URL/select a file.

![image](https://user-images.githubusercontent.com/439947/115028397-c86e0780-9e92-11eb-97a1-1573d04f291a.png)

In contexts that small groups/group sets don’t apply, that will, like today, be the end of the process—the user will be returned to the create/edit assignment form.

In contexts that do support (Canvas) group sets, the following interface is presented after content is selected. The configuring user may take one of two options here:

1. Click the “This is a group assignment checkbox” OR
2. Click the “Continue” button, which will complete the process and return the user to the create/edit assignment form

![image](https://user-images.githubusercontent.com/439947/115028414-d02dac00-9e92-11eb-8309-4655dbe0b8fc.png)

If the user selects the “This is a group assignment” checkbox, the “Continue” button is disabled until the user selects a group set from the resulting drop-down input:

![image](https://user-images.githubusercontent.com/439947/115028421-d3289c80-9e92-11eb-8333-79b9a2891648.png)

Once a group is selected, the “Continue” button is enabled (deselecting the “This is a group assignment” checkbox would also re-enable the Continue button, as above). Clicking “Continue” will complete the configuration process and return the user to the create/edit assignment form.

![image](https://user-images.githubusercontent.com/439947/115028431-d6238d00-9e92-11eb-82a8-52d76004b41d.png)

Goals of this approach:

* Extend, but do not replace the existing configuration process. The first step of this process will look almost exactly the same, function the same, and be the only step (as it is now) for any context in which Canvas group sets are unavailable.
* Try to adhere to the vocabulary (e.g. *Group set*) and interfaces (e.g. the drop-down group select) of the current LMS, where possible
* Be modular in approach to thinking about assignment configuration, as the list of possible steps is likely to increase in the future
