### ISSUE TITLE
Move Canvas assignments into the DB

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#2527]
Canva's assignments currently store all their configuration on the LTI launch URL as query params.

Follow the same pattern as other's LMS assignments and create/update/upsert a row in `ModuleItemConfiguration` per assignment.

This might be partially achieved by: https://github.com/hypothesis/lms/issues/2769

**Comment by seanh** [comment]
Unlike in non-Canvas LMS's, in Canvas at the time when the user is creating an assignment and they select the assignment's document there is no LTI assignment ID (`resource_link_id`) yet. We therefore cannot use the `resource_link_id` as the ID for the assignment's config in our DB. For non-Canvas LMS's we currently _do_ use the `resource_link_id` as the ID for looking up the assignment's configuration in the DB: https://github.com/hypothesis/lms/blob/01159673e5f7f10832a2efad5cc91786baee3bb7/lms/models/module_item_configuration.py#L31-L32 but we won't be able to do that for Canvas assignments.

Instead we are going to have to generate our own unique ID for the assignment and save that both in the DB and in the LTI launch params. We will have to submit a launch URL like this to Canvas: `https://lms.hypothes.is/lti_launches?hypothesis_assignment_id=<ID>`. When we receive an LTI launch we read the `hypothesis_assignment_id` from the query params and use it to look up the `ModuleItemConfiguration` in the DB and find the assignment's configuration (e.g. its document URL).

So this means that we have to both:

1. Make an API call to our own backend to create a new `ModuleItemConfiguration` in the DB. This API call should return a new `hypothesis_assignment_id`
2. Still submit an LTI launch URL to Canvas like we currently do. But instead of having the actual assignment configuration in the query params, it's just going to have the `hypothesis_assignment_id`

We better namespace the query param name (`hypothesis_*`) so it doesn't clash with any current or future Canvas launch params.

The first time an assignment is _launched_ (after having been created) we do receive the `resource_link_id` param, as well as our `hypothesis_assignment_id`. At this point we need to record the `resource_link_id` in the `ModuleItemConfiguration` in our DB, forever associating this `resource_link_id` and `hypothesis_assignment_id` with each other.

This is crucial for course copy. When a user copies a Canvas course all the Hypothesis assignments get copied into the new course and the new copies of the assignments get new `resource_link_id`'s. Given that the `resource_link_id`'s have changed, if we were using the `resource_link_id` to look up the assignment's configuration in our DB we would not find it. AFAIK Canvas does not provide any way (e.g. in the launch params) for us to find the `resource_link_id` of the original assignment or even to know that the assignment was copied.

Fortunately the assignment's launch URL gets copied into the new assignment un-modified, complete with `?hypothesis_assignment_id=<ID>` query param. So we can use the `hypothesis_assignment_id` to find the `ModuleItemConfiguration`. We can then look at the `ModuleItemConfiguration`'s `resource_link_id` and, if it differs from the `resource_link_id` in the launch params then we know we're seeing a copied assignment and we need to make a new copy of the `ModuleItemConfiguration` in our DB.

Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1621249716149100?thread_ts=1620901832.105300&cid=C4K6M7P5E
