### ISSUE TITLE
Handle Blackboard Files assignments whose file has been deleted

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2859]
## Problem

Note: There's already an assignment named **localhost (make devdata) Blackboard Files Assignment Whose File Has Been Deleted** in our [Blackboard test course](https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline) that you can just launch to reproduce this problem (you'll need to re-run `make devdata` in LMS first), so you don't actually need to follow these steps:

1. Log in to our test Blackboard site as a teacher, create a Blackboard files assignment, launch it, and select a file (using the <kbd>Choose PDF from Blackboard</kbd> button)
2. Now go and delete the selected file from Blackboard
3. Go back and launch the assignment

You will see a generic **Something went wrong** error dialog:

![Screenshot from 2021-06-22 11-25-31](https://user-images.githubusercontent.com/22498/122908934-95416c00-d34c-11eb-926f-799354d27a75.png)

You _should_ be seeing a more specific **Hypothesis couldn't find the assignment's PDF file in the Blackboard course** error message. The backend (`/via_url` API) is actually sending an error response (400 Bad Request) with this JSON body:

```json
{
  "message": "Hypothesis couldn't find the assignment's PDF file in the Blackboard course.",
  "details": {"document_url": "_9019_1"}
}
```

But the frontend no longer seems to make any use of the `message` sent by the backend.

There's a docstring documenting how the backend expects this to work here:

https://github.com/hypothesis/lms/blob/f70c0ccbdb2bbc006e93a92013599512c0125698/lms/views/api/exceptions.py#L25-L91

I can't remember whether the `message` string returned by the backend used to be used as the error dialog's title or its body text. I suspect it may have been shown in the body, in which case the error dialog _should_ look like this:

![Screenshot from 2021-06-22 11-30-35](https://user-images.githubusercontent.com/22498/122909670-565fe600-d34d-11eb-86c4-923f859f8a75.png)

Note that there are probably other error situations that are broken in the same way: just saying <q>There was a problem fetching this Hypothesis assignment</q> when the backend has actually supplied a specific `message`.

**Comment by robertknight** [comment]
It looks like this text:

> Something went wrong: there was a problem fetching this Hypothesis assignment

Corresponds to the `error-fetching` case in `LaunchErrorDialog` in the frontend. That in turn ends up rendering the server-provided error along with details and support link via `<ErrorDisplay error={error}/>`. Inspecting `ErrorDisplay` I see that it only renders the server-provided message if a `message` prop is passed to `ErrorDisplay`. That got removed in https://github.com/hypothesis/lms/commit/44c111c17a95f2f81747a8f6c9a48170d5767df1.

The fix here is to make it so that the rendering of the server-provided message doesn't depend on whether a `message` prop is passed to `ErrorDisplay`.
