### ISSUE TITLE
Implement frontend for OneDrive support

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2942]
<del>Depends on https://github.com/hypothesis/lms/pull/2937 which adds the JS config settings for OneDrive.</del> <ins>(merged)</ins>

Fixes https://github.com/hypothesis/lms/issues/2903

Implement the frontend code for OneDrive:

* When OneDrive support should be enabled the backend adds the OneDrive file picker config into the JS config. It looks something like this:

  ```json
  {
    "filePicker": {
      "microsoftOneDrive": {
        "enabled": true,
        "clientId": "<ONEDRIVE_CLIENT_ID>"
      }
  }
  ```

* When the `filePicker.microsoftOneDrive.enabled` setting is `true` the frontend should show the <kbd>Choose PDF from OneDrive</kbd> button:

* When clicked this button should open the OneDrive file picker

* The selected file should be sent to the backend as the assignment's document URL

See also:

* OneDrive proof-of-concept: https://github.com/hypothesis/lms/pull/2891
* OneDrive master issue: https://github.com/hypothesis/lms/issues/2903

**Comment by marcospri** [comment]
# File picker

OneDrive offers two different file pickers a "JavaScript" one:

https://docs.microsoft.com/es-es/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online

and a React one:

https://docs.microsoft.com/es-es/onedrive/developer/controls/file-pickers/react/?view=odsp-graph-online
https://www.npmjs.com/package/@microsoft/file-browser

the react ones is marked as "Preview" with a `This API is provided as a preview for developers and may change based on feedback that we receive. Do not use this API in a production environment.` notice. See https://github.com/OneDrive/onedrive-api-docs/issues/1089  for status updates on progress and some issues.

With that I went for the JavaScript one for the PoC which integrates very similarly to Google's Drive's. I think we rather use the old one and eventually upgrade rather than pick the unstable one and have to do a downgrade in a hurry if we find issues.


## File picker authentication

The file picker receives the `client_id` via the back end _js_config. It also needs to "land" in a page where its own code is present  (file picker loaded in SPA -> `filepicker.open()` -> file picker pop up with file picker object loaded) so the backend also provides an URL that just renders something like `<script>onedrive.js</script>`. There might be a nicer way to do the authentication without the need of that landing auth page but that's the approach taken on the PoC.

**Comment by robertknight** [comment]
>  I think we rather use the old one and eventually upgrade rather than pick the unstable one and have to do a downgrade in a hurry if we find issues.

That seems wise to me.
