### ISSUE TITLE
Handle creating Blackboard Groups assignments when the course has no group sets

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3480]
You could create a course with no group sets to test this or you could just simulate it:

```diff
diff --git a/lms/services/blackboard_api/client.py b/lms/services/blackboard_api/client.py
index e8acae7e..afeccd82 100644
--- a/lms/services/blackboard_api/client.py
+++ b/lms/services/blackboard_api/client.py
@@ -106,7 +106,7 @@ class BlackboardAPIClient:
             f"/learn/api/public/v2/courses/uuid:{course_id}/groups/sets",
         )
 
-        return BlackboardListGroupSetsSchema(response).parse()
+        return []
 
     def group_set_groups(self, course_id, group_set_id):
         response = self._api.request(
```

If you then try to create a groups assignment this currently results in a _Group set_ dropdown menu with no items in it. Instead it should show a helpful error message explaining to the user that the course has no group sets.

(P.S. Canvas groups probably has the same problem.)

**Comment by lyzadanger** [comment]
I'd like some assistance in writing copy for the message we show users. Right now, this is my starting point:

![image](https://user-images.githubusercontent.com/439947/151422791-30eb4899-9bb7-473a-9fb5-bd0ddf0f6d93.png)

We have complete control over the content and title of this modal. But I need some input!

**Comment by chrisshaw** [comment]
Both Canvas and Blackboard call them group sets so in general this seems like a good start. Feel free to modify based on available characters and whatnot.

I know some people don't like personifying these kinds of messages. I personally think it makes it more human, but feel free to take it or trash it.

I would go ahead and add the try again, because having the call to action is ideal and we then ought to make it easy to follow through.

---

**No group sets found**

Hypothesis relies on group sets to place students into groups. We could not find any available group sets in this course. Please add one or more group sets to your course and try again.

If the problem persists, you can open a support ticket or visit our [help articles on using groups](https://web.hypothes.is/?s=group&ht-kb-search=1&lang=%0D%0A%09%09).

**Comment by lyzadanger** [comment]
@chrisshaw Hi! Thanks for the input! What do you think about this variant?

![image](https://user-images.githubusercontent.com/439947/151809235-d867b02d-2fc4-4dc8-801e-0b6ec1943b9a.png)

This allows us to keep the final paragraph identical to the other error modals in the application (and avoids having to reimplement it as a one-off for this particular error. There's some baked-in logic that generates that text and support link — it pre-fills the support form with a bunch of error information — that _can_ be customized but may not be worth it in this case).
