### ISSUE TITLE
We need to research how to get a viewable canvas file url every time the student goes to the app.

### ISSUE THREAD

**Issue by dittonjs** [hypothesis/lms#38]

**Comment by dittonjs** [comment]
make xhr request then programatically insert iframe one we have the public viewing url.

**Comment by seanh** [comment]
The code isn't very readable, but our old lti app actually does this successfully:

https://github.com/hypothesis/lti/blob/f788c60cf595f5139140e573163125afb8df98fa/lti/views/pdf.py#L35-L67

(It does the API request server-server in Python, but doing it via XHR as you suggest would be better if possible)

Note that you need to make an API request to the Canvas API to get a public URL for the file _every time you want to show the file_. The public URLs expire over time, so you can't re-use them. (I recommend just getting a new one every time, rather than trying to keep track of how long until it expires.)

**Comment by nick-benoit14** [comment]
We can oauth and make an api call to get the temporary public viewable url for a canvas file.
