### ISSUE TITLE
Improve logging & metrics to generate meaningful internal-facing reports

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#394]
Currently, we're using https://lms.hypothes.is/reports, built by AJ for LMS app reporting. It aggregates the following info for all installs and all launches:

- Date and time
- Consumer key & shared secret
- LMS URL 
- Signup email address

The /reports page, aside from being user un-friendly, does not provide all of the info we need for outreach and support purposes. 

I found this doc titled [Edu metrics user stories](https://docs.google.com/document/d/1nuCi81XmWPZO9wg3KVmSU3pubPGHQ62ApzVWkQ-yEv8/edit), which appears to still be "in progress." Once we finalize that doc, this issue can serve as an Epic.

**Comment by hmstepanek** [comment]
I'd like to also note the performance on this endpoint is really bad due to a non-performant db query on the lti_launches db table. 
![image](https://user-images.githubusercontent.com/30059933/56996051-4cb90a00-6b58-11e9-9ac0-7841320efc4d.png)

[detailed trace in New Relic]https://rpm.newrelic.com/accounts/1385283/applications/76030703/transactions?tw%5Bend%5D=1556661348&tw%5Bstart%5D=1556056548#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f6c6d732e76696577732e7265706f7274733a6c6973745f6170706c69636174696f6e5f696e7374616e636573222c22225d&app_trace_id=ad85c28a-6b91-11e9-93d3-0242ac11000f_7345_10400

**Comment by robertknight** [comment]
https://lms.hypothes.is/reports has been removed. The need has been met via other means. This ticket itself is no longer useful, so I'm closing it.
