### ISSUE TITLE
What does the app do with `resource_link_id`?

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#413]
We've had a couple of partner reports because of problems with the `resource_link_id` LTI parameter. I believe the most recent report was out of Blackboard.

The `resource_link_iid` parameter is _required_ by the LTI spec (more info https://www.imsglobal.org/specs/ltiv1p1/implementation-guide). However, there seem to be cases where some LMSes—possibly when the application install is configured in particular ways—are not sending this parameter.

What would be helpful is to understand why our app requires it and what we do with it. It is, again, a required LTI param, but it helps to be able to explain to institution admins why _our application_ needs it and what it does with it.

**Comment by seanh** [comment]
"Resource link" is LTI-speak for "assignment".

`resource_link_id` is a unique ID for a particular "placement" of our app or "link to our app" within a course in LTI terms. In human terms it's an ID for an **assignment**. Other LTI params (that we _don't_ use) tell us other things about the assignment, e.g. `resource_link_title` is the title of the assignment, and `resource_link_description` is the assignment description, as entered into the LMS by the teacher when creating the assignment.

When you create an assignment using our app you choose a document (HTML URL, PDF URL, Google Drive PDF, or Canvas Files PDF) to go with the assignment. Our app has to save the choice in its database so that it knows what document to show whenever someone launches the assignment. Our app uses the assignment's `resource_link_id` in order to identify which previously saved document from our DB goes with the assignment currently being launched. In other words `resource_link_id` (think "assignment ID") is how our app knows _which_ assignment is being launched.

In some cases, where the LMS supports LTI "content item selection", our app doesn't have to save the chosen document to its DB because the LMS supports saving the choice for us. In this case we don't need `resource_link_id`. At least some methods of using the app in Canvas support this for example. But other LMS's (e.g. Moodle and Blackboard, I think) don't support this so we have to use `resource_link_id` instead.
