### ISSUE TITLE
Open links in a new tab in the LMS app

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#451]
I discovered this when a prof asked me if a HTML list of poems with links to the poem themselves would work as a Canvas reading.

http://www.victorianweb.org/authors/henley/inhospital/contents.html

While the initial URL, the list of poems works in the app--class and user identities match with Canvas course shell--navigating to the other URLs that actually contain the poems breaks the SSO. The public group is open on the page and I'm asked to log in normally.

![image](https://user-images.githubusercontent.com/3261902/52455748-485ff080-2b17-11e9-8a5c-baedeb1c4cb7.png)

While it would be great for this prof and this particular use case if the SSO held through navigation, I'm not sure if that could work or is the best workflow. Clearly, though, it is not good for someone to suddenly be in the public H namespace upon navigation from a H-enabled URL in Canvas: very confusing for user; very possible since URL docs are one of the primary means of annotating in class; potential FERPA violations (though it would take work on the students part).  

Note navigating back to the previous URL causes this error but reloading the page does put me back in the SSO world. 

![image](https://user-images.githubusercontent.com/3261902/52455892-ec499c00-2b17-11e9-9593-00416a00572d.png)

 You can see this for yourself in our Canvas at this page:

https://hypothesis.instructure.com/courses/46/modules/items/658

**Comment by seanh** [comment]
Hmm, not a quick fix unfortunately, this is a use case that we hadn't considered and don't yet have any support for.

**Comment by jeremydean** [comment]
It's not the initial use case we should necessarily focus on.

It's the fact that SSO can be broken by a click in the use of the app.

**Comment by seanh** [comment]
Had a chat with Rob and Hannah about this. Two things we could do are:

1. Add some JavaScript to Via that makes all links open in new tabs and with no client embedded in those new tabs at all.

   This would prevent you from browsing to new pages within the LMS. So it'd prevent you from breaking it. But it wouldn't enable the user to do what they're trying to do in this case. Users may still see it as broken.

   This should be a fairly small change to make.

2. Allow it to browse to new pages within the LMS (as it does currently) but keep the login and groups integration working. This would require both adding some JavaScript to Via and adding a new feature to the LMS app. It's medium-to-big job, but not huge.

If we went with (2) then we're allowing users to create annotations on different websites or web pages as part of a single assignment. This is going to make our lives much more difficult, and create more work for us to do, when it comes to implementing things like grading support in the future. Because the grading feature will have to find all the annotations, even though they aren't on the assignment's original document. Not saying it can't be done but it certainly makes future features more complicated and difficult.

For that reason I'm wondering if we should do (1)?

**Comment by jeremydean** [comment]
Yeah, I'd want to think more about whether 2 is worth it. I could see multiple use cases including and beyond the one that tipped this issue, but don't know that they're mainstream enough to prioritize as a feature.

1 seems advisable and I think if H is not embedded in the new tab then it won't seem as broken as it currently does.

**Comment by judell** [comment]
Number one sounds like a good solution, thank you Sean.

**Comment by seanh** [comment]
Ok. So this is a known issue with the app, with an agreed-on solution. Just needs to be priortised relative to other issues and we can get it into a sprint

**Comment by klemay** [comment]
Pointing out a use case from https://hypothesis.zendesk.com/agent/tickets/4091 which is pretty common among humanities courses:

> In the old version [of the Hypothesis LMS app], I sent them to this page:
> 
> http://nineteenthcenturydisability.org/items/browse 
> 
> And then students would wander around this site as though visiting a museum, and would choose a page, and would annotate the "display". 

Many digital humanities projects are set up to be a showcase of artifacts, and an instructor is likely to want students to browse through multiple artifacts. In this case, the instructor would need to create a separate Hypothesis assignment for each one, and students would have to close the assignment and open another one each time they want to annotate a new artifact.

I'm not saying we should change our decision on approach 1 vs 2, but wanted to make sure we are aware of this kind of use case.

**Comment by seanh** [comment]
Since everyone seems to have forgotten about this for months, I'm assuming it's not actually high priority

**Comment by mkdir-washington-edu** [comment]
ZD tickets:
https://hypothesis.zendesk.com/agent/tickets/7344
https://hypothesis.zendesk.com/agent/tickets/7261
https://hypothesis.zendesk.com/agent/tickets/7247
https://hypothesis.zendesk.com/agent/tickets/6477
https://hypothesis.zendesk.com/agent/tickets/5369

**Comment by seanh** [comment]
Article on new third-party cookie default policy changes coming to browsers, potentially relevant to some ways we might implement this: https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by mkdir-washington-edu** [comment]
There are two reasons why I think this is something important to fix, and if (1) is the easier solution we should go with it:

- Users get confused by the fact that there is no discernible difference between the LMS app and the "non-LMS app", and so when they end up breaking SSO they assuming the LMS app is broken in some way.
- Instructors are using OER textbooks, and want to assign groups of chapters in a single assignment, which necessitates clicking a link.

While I don't know the difficulty in implementing one solution or another, I think even killing all of the links on an LMS assignment would be fine, since then there's no change for users to get kicked out of the LMS app.

**Comment by klemay** [comment]
I've renamed this issue to reflect that we've agreed on a solution: when users click a link while viewing an HTML assignment, those links should open in a new tab or window.

**Comment by robertknight** [comment]
Implemented by https://github.com/hypothesis/lms/pull/1770 and https://github.com/hypothesis/via/pull/235. @jon-betts - We will need to re-implement this functionality in Via 3 when we move HTML proxying away from legacy Via.
