### ISSUE TITLE
SPIKE: How does course copy work currently on Canvas

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4877]
### How the course copy files fix works in canvas

- The moment when an instructor configures an assignment with Canvas files, we store all the files metadata (for every file in the course) in our DB.
- Students might have access to the `list_files` API endpoint or not. One way to simulate this is to limit visibility of  the files section in Course -> Settings -> Navigation.

The process is then:

- An instructor configures the original assignment to use canvas files. In that moment we store all the files in our DB. The assignment points to file ID `ORIGINAL` 

- The course gets copied, the new assignment still points to `ORIGINAL`.

#### If an instructor launches the new assignment first:

1. Check if we have a mapping stored that points `ORIGINAL` to another file

2. We check that the file `ORIGINAL` belongs to the new course

3. That check fails

4. We query all files from the new course (and store them in the DB)

5. For each file in the new course we check if we find a match in the DB, if we do we point `ORIGINAL` -> `NEW` and store that in the DB.

6. If we don't find a match we show the Error dialog about not having access to the file.

#### Any subsequent launches of the same assignment, by any user:

1. Check if we have a mapping stored that points `ORIGINAL` to another file
2. Return the mapped file, `NEW`

#### If a **student** launches an assignment before the teacher and the student **has access to list the files** in the new course:

Same process as for the teacher, except we don't check that the file `ORIGINAL` belongs to the new course.

#### If a **student** launches an assignment before the teacher and the student **doesn't have access to list the files** in the new course:

We show an error dialog

**Comment by seanh** [comment]
@marcospri This is super helpful. I think we can close the issue now as the spike is completed? The closed issue will still be around for reference

**Comment by seanh** [comment]
Do we only store file metadata about the course when an instructor _configures_ an assignment? Or we also do it when they launch an assignment?

When do we _update_ our file metadata about a course? Since feels can be added, updated, renamed, deleted in Canvas

**Comment by marcospri** [comment]
> Do we only store file metadata about the course when an instructor configures an assignment? Or we also do it when they launch an assignment?

Only when configuring.


> When do we update our file metadata about a course? 

Just when configuring, we don't handle deletions, just new and updated files.

**Comment by mattdricker** [comment]
What happens if there is more that one file match in the new course?

We have seen cases where an instructor will have multiple copies of the same PDF in Canvas, but only one is "published". Or one copy has crappy OCR, so the instructor re-OCRd the doc, etc. (This is also why folder browsing is important, as often the instructor will organize based on folders.)

Also, does this process require that the original course/file is still accessible? From the descriptions it sounds like: no. Once we have captured metadata we never need to go back to the orig course.

**Comment by seanh** [comment]
> What happens if there is more that one file match in the new course?

We'll pick one of them, somehow. The reasoning is that if two files have the same name and the exact same file size then (we assume) they are literally the same file even if there are two copies of it. So it doesn't matter which one we match with. I'm guessing we just pick whichever one comes out of our database first, which may amount to whichever oneCanvas's API returned first or it may be more complicated than that.

> We have seen cases where an instructor will have multiple copies of the same PDF in Canvas, but only one is "published"

We hopefully only consider published files when looking for a match, but @marcospri would need to double-check that.

> Or one copy has crappy OCR, so the instructor re-OCRd the doc

To find a match we look for a file that has the same filename and size. If there's a crappy OCR'd copy and a re-OCR'd copy they would have different filesizes. So if the assignment pointed to the crappy OCR'd copy in the old course then it would only match with the crappy OCR'd copy in the new course, and vice-versa.

> does this process require that the original course/file is still accessible? 

No, because we already have a record of the original file's name and size in our DB from when we saw it.

**Comment by marcospri** [comment]
> What happens if there is more that one file match in the new course?

> Or one copy has crappy OCR, so the instructor re-OCRd the doc

We are kinda hoping same name and size is the same file. We could eventually add another layer "it's in the same named folder" which would make it even more unlikely to have a false positive. False positives are likely to happen from time to time but the "same size" check will probably rule out different actual files, just copies of the same file.

For Canvas that will have to come after we support folder in the file picker.

> We have seen cases where an instructor will have multiple copies of the same PDF in Canvas, but only one is "published"

Not sure, I'll have to test that. I reckon the same concern will apply to general usage of the files, not just while in course copy.

> does this process require that the original course/file is still accessible?

No, we rely on our stored metadata.
