### ISSUE TITLE
Should the activity emails contain the user's own activity?

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/lms#4925]
# Question

[Slack thread](https://hypothes-is.slack.com/archives/C04J58NGMC4/p1674063738693909).

Note that if we have to remove the user's own activity from the email that means that every single user's email is different from everyone else's. (They may already have been different anyway since each user is likely to be subscribed to different assignments and courses.)

If the only activity on an assignment is the user's own activity then we probably don't want to send them an email about that.

# Answer

I think this still needs a solid answer from product. Provisional answer from Lyza:

* Yes the email should contain your own activity
* Not sure whether or not we should send the email if it contains _only_ your own activity

**Comment by darylhedley** [comment]
- Decided to not include your own activity.
- Only count students
- Product work to add a section for instructors if this comes up from the pilot

**Comment by seanh** [comment]
My understanding of what we agreed in today's meeting:

* Ideally we would like the email to count **student** annotations only when it says <q>Your students made 64 annotations in 8 assignments</q> and <q>Students made 30 annotations in 2 assignments</q>. Ideally this will not count instructors--either the email recipient or other instructors.
  * If it turns out to be technically difficult to filter out other instructors then it's acceptable for these numbers to count annotations and replies from other instructors even though the wording says "students". But they must not count the recipient's own annotations or replies.
* We would like to some extra text to the email counting annotations and replies from other instructors. <q>There were also 6 annotations and 2 replies from other instructors</q> or something (actual text to be written). If this separate instructor count is technically difficult to do then we can omit it from the first version.

^ All of the above is subject to change if we change our minds or if we find out that parts of it are technically difficult to do.

**Comment by seanh** [comment]
Closing this for now as I think we have at least a provisional decision, we can still re-open this or comment on the closed card in future
