### ISSUE TITLE
Improve accessibility for grade input validation errors

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#5205]
Validation errors for the grade input field are displayed in a "toast message"-type control next to the grade input. There is no mechanism to communicate the validation error to assistive technology, either via an `aria-live` region, HTML form validation attributes etc.

Current display:

<img width="576" alt="Grade input validation message" src="https://user-images.githubusercontent.com/2458/226344984-c0764af5-840a-44c1-8e29-f63c765e72ce.png">

**Comment by robertknight** [comment]
The obvious fix here is wrapping up the `ValidationMessage` component in a `role=alert` element. That's not enough though because when the component is dismissed, the message actually remains in the DOM but just visually hidden. Hence if you trigger the same alert a second time, the message doesn't get read out. The reason for keeping the message in the DOM is due to an entry/exit transition that the component has.

**Comment by acelaya** [comment]
I think using `TransitionComponents` it should be possible to unmount the toast message once the transition has ended.

Also, we might want to use frontend-shared's `Callout` here for visual consistency with other Toast messages.

Additionally, we might want to revisit the type of the `input`. Using `input[type=number]` would add some a11y improvements out of the box.

**Comment by robertknight** [comment]
> Additionally, we might want to revisit the type of the input. Using input[type=number] would add some a11y improvements out of the box.

+1 for looking into this. That control has spin buttons by default, which I think we probably don't want to show visually here (probably still OK if the control is identified as a spinbutton as its ARIA role).

**Comment by acelaya** [comment]
I have spent some time thinking on this issue, and I have realized the only reason we need this validation toast message is to notify if the value is empty, or if the value is higher than `scoreMaximum`.

If we convert the input to `[type="number"]` and add `max={scoreMaximum}` and `required` attributes, we can achieve the same goal, making it more accessible in general, and would allow to get rid of the validation function, a few local state pieces, and the validation message component.

There are two problems though:
1. The toast message is (or has the potential to be) nicer than the native form validation.
2. In order to make native validation to apply, we need the form to be actually submitted, which means the two existing "submit" buttons need to become actual `[type="submit"]`. This is ok, but I have realized there's a problem if we do this with the button which is inside the comment popover.
    So far we were closing the popover on submit. If we do that now, it apparently doesn't triggers a form submit, because the button is unmounted.
    I have verified it works if we do not close the popover, or if we close it on the next tick (`setTimeout(..., 1)`).

One possible solution for number 2 is no longer closing the popover on submit, and let it close once the user moves to next student, but I'm trying to better understand the problem and see how is it supposed to be handled.

I also want to try if programmatically checking the form's validity via `reportValidity` does the trick.
