### ISSUE TITLE
Create QA LMS test data to staging LMS environment

### ISSUE THREAD

**Issue by leedenison** [hypothesis/lms#5546]

**Comment by robertknight** [comment]
We have set up new staging environments. @seanh can comment on how we kept our existing QA assignments working in the process.

**Comment by seanh** [comment]
We:

1. Copied the DB contents from LMS QA to LMS staging
2. Copied the envvars from LMS QA to LMS staging, and adjusted them appropriately
3. Pointed the old `qa-lms.hypothes.is` domain name at the new staging environment (in addition to the new `lms.staging.hypothes.is` domain name) so that all sorts of third-party systems (LMS's etc) that are configured with the old domain name keep working and don't need to be reconfigured
