### ISSUE TITLE
Style Canvas Pages to resemble the presentation in Canvas itself

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#5746]
Canvas pages are currently styled with the browser defaults.

The HTML returned by the API does include references to some CSS classes but no apparent way to link to the original stylesheet.

A possible workaround could be to serve ourselves a version of the same CSS canvas uses and tweak the HTML to match the same CSS classes.

See an attempt to do exactly that here:  https://github.com/hypothesis/lms/pull/5745

And further discussion in: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1696335428373059

**Comment by robertknight** [comment]
Per discussion in https://hypothes-is.slack.com/archives/C4K6M7P5E/p1696346206985649?thread_ts=1696335428.373059&cid=C4K6M7P5E, the plan is for me to make a more polished version of https://github.com/hypothesis/lms/pull/5745, along with documentation of how to update CSS in the future.

Canvas is AGPL licensed so re-using their code directly would generally not be possible. In this instance we're planning to redistribute a very small amount of compiled CSS in order to ensure that users' content looks the same or very close to how it looks in Canvas itself, when an assignment is served in our LTI tool. I think this is unlikely to cause issues, but just to be safe the plan is to separate any imported CSS into a separate directory and document clearly where it comes from, so that we can replace it if needed in future.
