### ISSUE TITLE
SPIKE: using Google file picker with institution-only PDFs and Team Drive

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#632]
**Note: this is being re-added to the "To Review" column on the Product backlog board because it was added to a sprint and then removed - we need to re-prioritize it among our other work.**

User story:
_As a teacher at Example University, I want to use the Hypothesis LMS app in Sakai to assign readings to my students. The PDFs for these readings reside in a [Team Drive](https://drive.google.com/drive/shared-drives), and the university library mandates that these PDFs are set so that "anyone at Example University with the link can view," rather than "anyone with the link can view."_ 

Currently, when a teacher selects a PDF from Google Drive, we set the privacy of that file to "anyone with the link can view." If you go back and manually change the privacy of the file to "anyone at [institution] with the link can view," launching the assignment will take you to a Drive login page. 

We need to look into:

- [ ] Does the Google Drive API allow for creation of a temporary public link which could be used by our app (the way the Canvas Files API currently works in our app)? If not, is it possible for our Picker to set the privacy of the link to "anyone at [institution] can view" by default?
- [ ] What will it take to get our file picker to support Team Drives? (This might be helpful: https://developers.google.com/drive/api/v3/enable-shareddrives)

**Comment by seanh** [comment]
@klemay Can we have a screenshot of what happens If a PDF *does* have _Downloading, printing, and copying_ enabled, but it is set to _anyone at Example University can view_?

**Comment by seanh** [comment]
I believe this is a screenshot of what happens if:

1. The PDF's share link in Google is set to _anyone with the link can view_, but
2. _Disable options to download..._ is checked

<img width="851" alt="Screen Shot 2019-05-21 at 6 33 01 PM" src="https://user-images.githubusercontent.com/22498/58166185-2bdc6400-7c81-11e9-9bc7-44ac1cd30ce7.png">

**Comment by klemay** [comment]
Ok, this might be helpful so documenting here.

I created an assignment using the Google Picker for a PDF in my drive that was not shared with anyone. After the assignment was created, that PDF's settings were changed to "Anyone with the link can view." I went back and manually set the PDF to "anyone at Hypothesis who has the link can view." When I went to re-launch the assignment, this is what I ran into:

<img width="1143" alt="Screen Shot 2019-06-13 at 12 02 15 PM" src="https://user-images.githubusercontent.com/12087705/59448433-1e734f00-8dd3-11e9-870b-3a18782dcf46.png">

**Comment by klemay** [comment]
Another potential complication - the partner institution is using a Shared drive for these files, which would require changes to our picker, it looks like: 

https://developers.google.com/drive/api/v3/enable-shareddrives

**Comment by robertknight** [comment]
The solution I had in mind here is to make Google Drive files work similar to Canvas files, with the difference that I don't think we are able to serve the PDF download URL through Via but will instead need to load the content into PDF.js another way.

A sketch of the changes this would involve:

1. Change the Google Drive assignment selection flow so that it records the file ID but doesn't make the file publicly accessible. In other words, it would generate an LTI launch URL similar to the one it generates for Canvas files.
2. Change the assignment launch flow for Google Drive files so that instead of directly rendering a PDF in Via, it instead:
  - Gets the user's authorization to access their files in Google Drive
  - Fetches the file content
  - Serves the file content inside PDF.js, eg. using a blob URL or by passing a data buffer directly to PDF.js

What this will allow is for any file that is shared with the student's Google account, eg. by being shared with "anyone at <institution>" to be used as an assignment without needing public sharing.

A completely different approach would be to fetch the file content at the time the teacher chooses the assignment, store it somewhere on our backend, and serve it when the student creates the assignment. This approach obviously comes with copyright complications since the content would end up, at least for a period of time, on our servers. For that reason I'm inclined to go with the first option outlined above.

**Comment by klemay** [comment]
@robertknight thanks for this - the implementation you've outlined makes sense. I'm going to close this spike and open an issue based on your comment so it can be prioritized among our other work.

**Comment by robertknight** [comment]
Hi @klemay - I still think it would be worth doing a spike based upon my suggestion above to check that it does actually work and that there aren't any major issues I've failed to consider.

**Comment by seanh** [comment]
FYI, I think we are going to need a standalone CORS proxy server for PDFs. Currently this is Via:

* Google Drive and other file hosts don't include the necessary CORS headers to allow JS to download their PDFs, IIRC
* The LMS app shouldn't download PDFs to its server and re-host them IMO. This means that the LMS app is spending a long time doing these long downloads. The browser has to wait the entire time for the download to our hard drive to complete and _then_ they can _start_ downloading the file from us. It'd require a persistent storage attached to the LMS app's app servers (which while possible is not something any of our apps currently have). Storage space issues and having to delete older files. Copyright issues ... It makes more sense to do Via-style proxying without persistence or caching on our servers. (This is why we changed Jon's original LTI app, which did download PDFs to its hard drive, to use Via instead.) But just implement a better, faster, simpler version of it

**Comment by robertknight** [comment]
> Google Drive and other file hosts don't include the necessary CORS headers to allow JS to download their PDFs, IIRC, so I don't think the blob or data URL thing will work. 

I've just checked and this is not a problem for Google Drive. See [Slack discussion](https://gist.github.com/robertknight/c831ba788cf850be97ac50006ee3540d). The Google API JS client is able to fetch file content from Google Drive files. It does so in an elaborate way that doesn't involve making a CORS request, but the end result is that the frontend app can fetch data from Google Drive without needing any server-side help from a proxy.

We will however still need a proxy for serving PDFs from arbitrary URLs entered in the "Enter URL" dialog in the file picker.

**Comment by klemay** [comment]
@robertknight sorry for getting a little over-eager with closing this issue. I've converted the new issue to a spike: https://github.com/hypothesis/lms/issues/928
