### ISSUE TITLE
New document selection frontend fails when document URL has non-ASCII chars

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#689]
There's an issue with the new file picker that, when a public HTML URL assignment is created, if the URL contains non-ASCII characters then launching the assignment fails with _You're not authorized to view this page_. Even if you turn the feature flag off launching the assignment will still fail if the flag was on when the assignment was created. But if the flag was off during assignment creation then it works.

There's a difference in escaping of the URL that might be suspect. With an assignment created with the feature flag off the LTI launch URL (copied from dev tools) is `https://lms.hypothes.is/lti_launches?url=https://en.wikipedia.org/wiki/G%C3%B6reme_National_Park`. With the flag on it's` https://lms.hypothes.is/lti_launches?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FG%25C3%25B6reme_National_Park`

**Comment by robertknight** [comment]
I wasn't able to reproduce this just now using my local lms dev environment in the Canvas instance at https://hypothesis.instructure.com. Looking at the two URLs you posted, the second one, as used when the feature flag is on, actually looks correct to me - the `url` param has been encoded as a whole.

I tested it as follows:

1. Go to https://en.wikipedia.org/wiki/Göreme_National_Park in Chrome
2. Copy the URL from the URL bar and paste it into the "Enter URL of web page or PDF" form in the new picker
3. Accept the URL
4. Launch the assignment

In step (3), the generated LTI launch URL was https://localhost:8001/lti_launches?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FG%C3%B6reme_National_Park

In step (4) the Via iframe URL was https://localhost:9080/https://en.wikipedia.org/wiki/Göreme_National_Park?via.open_sidebar=1&via.request_config_from_frame=https%3A%2F%2Flocalhost%3A8001

**Comment by robertknight** [comment]
After some back and forth on Slack, we've established that the difference here is due to the way that the URL copied from the browser is represented when pasted into the file picker's input field. On my system, the text is pasted as Unicode. On Sean's system, the pasted URL is percent-encoded.

In theory, it should be fine if the URL is percent-encoded when pasted, as it represents the same URL. However it looks like attempting to launch fails with an HTTP 403:

```
2019-07-05 11:59:03,164 INFO  [pyramid_debugtoolbar:268][MainThread] Squashed pyramid.httpexceptions.HTTPForbidden at https://localhost:8001/lti_launches?url=https%3A%2F%2Fen.wi
kipedia.org%2Fwiki%2FG%25C3%25B6reme_National_Park
```

And the following message in the `_debug_toolbar` link:

```
pyramid.httpexceptions.HTTPForbidden: Unauthorized: BasicLTILaunchViews failed permission check
```

**Comment by robertknight** [comment]
It looks like the problem is pylti / python-oauth2's handling of query parameters in the OAuth launch request that contain percent-encoded characters:

```
>>> import pylti.common as pylti
>>> pylti.Request_Fix_Duplicate
<class 'pylti.common.Request_Fix_Duplicate'>
>>> pylti.Request_Fix_Duplicate.from_request('GET','https://example.com/', parameters={'url': 'https://en.wikipedia.org/wiki/G%C3%B6reme_National_ark'})
{'url': 'https://en.wikipedia.org/wiki/G%C3%B6reme_National_ark'}
>>> pylti.Request_Fix_Duplicate.from_request('GET','https://example.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FG%25C3%25B6reme_National_ark', parameters={'url': 'https://en.wikipedia.org/wiki/G%C3%B6reme_National_ark'})
n
{'url': 'https://en.wikipedia.org/wiki/Göreme_National_ark'}
```

Since the "url" param is present in both `self._request.url` and `self._request.params`, removing the "url" param from the query params and passing it only in the `parameters` kwarg resolves the issue. This is demonstrated using the following hack:

```diff
diff --git a/lms/services/launch_verifier.py b/lms/services/launch_verifier.py
index 54c257d..bfc48c5 100644
--- a/lms/services/launch_verifier.py
+++ b/lms/services/launch_verifier.py
@@ -61,9 +61,11 @@ class LaunchVerifier:
         consumers[consumer_key] = {"secret": shared_secret}
 
         try:
+            import re
+            verify_url = re.sub('\?.*', '', self._request.url)
             valid = pylti.common.verify_request_common(
                 consumers,
-                self._request.url,
+                verify_url,
                 self._request.method,
                 dict(self._request.headers),
                 dict(self._request.params),
```
