### ISSUE TITLE
Provide a helpful error message and details when the LMS URL is wrong

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#767]
When you register at https://lms.hypothes.is/welcome you have to enter your **LMS Domain**. This domain is used as the domain for our server to send requests to, and also to direct the authorization popup window to, when using the Canvas API. If you enter this domain wrongly (e.g. just enter example.com) then when you try to create a Canvas file assignment you get stuck in an _Allow file access_ loop:

![Peek 2019-07-05 16-35](https://user-images.githubusercontent.com/22498/60732809-eaf39280-9f42-11e9-8ca4-9d24d1987a37.gif)

We may not be able to do much about the wrong page showing up in the popup window, but we should at least be able to provide a better error message when the list_files request fails.

Related: [Validate LMS URL's on the /welcome page](https://github.com/hypothesis/lms/issues/592)

**Comment by hmstepanek** [comment]
This happens when it is the first time the user has tried to access their files (as shown above in the gif). The authorize message appears because the user does not have an oauth2 token yet and so it fails out before a request is even sent to canvas for the files. It fails on a self._oauth2_token attribute doesn't exist on [this line]( https://github.com/hypothesis/lms/blob/74eacedb5d03931d80fe267413426c851a5eb1e1/lms/services/canvas_api.py#L88).

**Comment by hmstepanek** [comment]
I started a slack thread on this [here](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1565124134028700). I'm not sure where to go from here so I'll await feedback from the team.

**Comment by robertknight** [comment]
Fixed in https://github.com/hypothesis/lms/pull/941
