### ISSUE TITLE
Research compatibility of app with LTI 1.3 

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#850]
We were told today at Blackboard World that IMS will be deprecating all LTI versions previous to 1.3. We should research the implications for our app. Are we compatible with LTI 1.3? It also sounds like this will effect IMS certification.

https://www.imsglobal.org/lti-security-announcement-and-deprecation-schedule-july-2019

@klemay @seanh

**Comment by robertknight** [comment]
Extracting the notable dates from that press release:

- OAuth 1.0a signing must use SHA-256 rather than SHA-1 to qualify for certification after 31st December 2019. The [LTI request signing implementation](https://github.com/mitodl/pylti/blob/18a608282e0d5bc941beb2eaaeea3b7ad484b399/pylti/common.py#L280) that we currently use uses HMAC-SHA1, so this potentially affects us. If we need to make a change here we should do that as part of https://github.com/hypothesis/lms/issues/778
- For certification after 31st December 2019, we need to implement either LTI 1.3 or a ["Security Update" to LTI 1.1](https://www.imsglobal.org/spec/lti/security-update/v1p0). The "Security Update" does not explain what issue exactly is mitigated, but it mentions an XSRF attack. A detailed explanation with worked example of the security issue can be found here: https://community.brightspace.com/s/article/Update-on-LTI-Vulnerability-LTI-Launch-with-New-Security-Requirements
- For certification after mid-2022 we need to be implementing LTI 1.3 or later

**Comment by robertknight** [comment]
> Are we compatible with LTI 1.3? 

I had a read through of the LTI 1.3 specs this morning [1]. In short, implementing LTI 1.3 is a substantial project. Our "LMS" application is currently an "LTI 1.0/1.1 Tool Provider". LTI 1.3 preserves many of the basic concepts of LTI 1.1, but the security protocols on which it is built are different [2], and this significantly changes the registration process, flow of execution when launching an LTI assignment, and methods used by the LTI tool to pass back grades and other information to the LMS.

The LTI 1.3 specifications are quite recent and Canvas has only just implemented LTI 1.3 + associated specs for grading and other extensions ("LTI Advantage") behind a feature flag.

[1] The specs are comprised of [IMS Security Framework](https://www.imsglobal.org/spec/security/v1p0/) which explains how the LTI tool and the LMS communicate securely, the [LTI 1.3 core specification](https://www.imsglobal.org/spec/lti/v1p3/) which explains how a basic "External tool" assignment/content is created using LTI 1.3 and additional specifications which cover "deep linking" and reporting of grades/progress from the LTI tool back to the LMS.

[2] In technical terms, LTI 1.0/1.1 uses OAuth 1.0, LTI 1.3 uses OAuth 2 and OpenID Connect. LTI 1.3 also has a more complex launch flow to fix a security issue with LTI 1.0 where a malicious student (call them Mallory) could, in theory, trick another student (call them Alice) into doing an assignment under Mallory's identity.

**Comment by robertknight** [comment]
Some of the authenticated changes in LTI 1.3 have been "backported" to LTI 1.0/1.1, presumably as a way to provide something easier for LTI tools to implement in a shorter time frame.

**Comment by robertknight** [comment]
I think the above comments answer the question "Are we compatible with LTI 1.3?" from the initial issue. The TL;DR is "no, and it looks like quite a lot of work to implement."

I think the next steps here are:

1. Establish any deadlines/timelines that we need to be aware of with respect to certification etc. I've mentioned Jan 1st 2020 as a deadline for implementing the LTI 1.1 Security Update in order to achieve IMS certification after that deadline.
2. Create a spike to implement the [LTI 1.1 Security Update](https://www.imsglobal.org/spec/lti/security-update/v1p0#lti-launch-authorization-flow). It looks like this may be a small-enough amount of work compared to LTI 1.3 that it would be worth doing before we come to LTI 1.3. This also involves investigating the support for this change with the various major LMSes.
3. Create a spike to implement the most basic possible implementation of LTI 1.3 alongside LTI 1.1

**Comment by klemay** [comment]
Thanks, Rob! I created the two spikes you suggested:

- LTI 1.1 security update: https://github.com/hypothesis/lms/issues/876
- Basic implementation on LTI 1.3: https://github.com/hypothesis/lms/issues/877
