### ISSUE TITLE
SPIKE: Are there other feasible, more meaningful dates to use for user submissions?

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#880]
The API for creating "user submissions" of Canvas assignments is a bit fiddly regarding date of submission, so at present a hard-coded date is used (December something, 2000 IIRC). Do a little spelunking to see if there is a more "meaningful" date that could be used, easily.

**Comment by robertknight** [comment]
In summary, there are no obvious assignment-related dates easily available from the current sources of information we have in an LTI launch, which persist from one launch to the next. We could however modify the configuration for new LTI installs, and provide documentation for how to reconfigure existing ones, so that our app gets information about an assignment's due date. We could for example use that info in the grading view to highlight annotations added after the due date.

The one thing we could easily do is change the current dummy submission date to any other fixed date. It is currently set as Dec 31st 2000 with the intention that this appears to a user to obviously be a dummy date.

I'm going to close this for the moment as I think we need more input from stakeholders that this is important enough to work on over other things.

----

**Investigation notes**

There are a few possible sources of relevant dates we could look at to use for a submission date, as long as our UI doesn't have an actual "Submit" button that students have to click:

1. **LTI Launch parameters**. I had a look at these and I couldn't see any useful dates here (e.g. due date of assignment) which would be the same across launches of an assignment. It looks like it would be possible to add [extra custom parameters to the LTI launch](https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html) for the due date. However that won't work for existing installs. It might be useful info to have in the SpeedGrader launch though, as we could use it to indicate when an annotation was last created or edited after the due date.

Example current LTI launch params:

<details>
```
oauth_consumer_key: Hypothesis09f2104b7e7321018291c65f316dc6a7
oauth_signature_method: HMAC-SHA1
oauth_timestamp: 1565707996
oauth_nonce: Q8W8NasyDH8PLG932ZopFzh9kUoZTdgdXoTTcNCMpUA
oauth_version: 1.0
context_id: c6163de28886ad7d128ba07a24692a54978e54f2
context_label: SpeedGrader
context_title: SpeedGrader Testing
custom_canvas_api_domain: hypothesis.instructure.com
custom_canvas_assignment_id: 518
custom_canvas_assignment_points_possible: 0
custom_canvas_assignment_title: HTML (Example.com)
custom_canvas_course_id: 89
custom_canvas_enrollment_state: active
custom_canvas_user_id: 34
custom_canvas_user_login_id: robertknight+student@hypothes.is
custom_canvas_workflow_state: available
ext_ims_lis_basic_outcome_url: https://hypothesis.instructure.com/api/lti/v1/tools/324/ext_grade_passback
ext_lti_assignment_id: 841a7d41-0922-43a0-88cb-2bc5af805371
ext_outcome_data_values_accepted: url,text
ext_outcome_result_total_score_accepted: true
ext_outcome_submission_submitted_at_accepted: true
ext_outcomes_tool_placement_url: https://hypothesis.instructure.com/api/lti/v1/turnitin/outcomes_placement/324
ext_roles: urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Learner,urn:lti:sysrole:ims/lis/User
launch_presentation_document_target: iframe
launch_presentation_locale: en-GB
launch_presentation_return_url: https://hypothesis.instructure.com/courses/89/external_content/success/external_tool_redirect
lis_outcome_service_url: https://hypothesis.instructure.com/api/lti/v1/tools/324/grade_passback
lis_person_contact_email_primary: robertknight+student@hypothes.is
lis_person_name_family: (Student)
lis_person_name_full: Robert (Student)
lis_person_name_given: Robert
lis_result_sourcedid: 324-89-518-34-522d13b2bbcdb84212a8502ff471e3490550baf8
lti_message_type: basic-lti-launch-request
lti_version: LTI-1p0
oauth_callback: about:blank
resource_link_id: 81a833a24a85859c4172ec7742f651eaaab9b2ee
resource_link_title: HTML (Example.com)
roles: Learner
tool_consumer_info_product_family_code: canvas
tool_consumer_info_version: cloud
tool_consumer_instance_contact_email: notifications@instructure.com
tool_consumer_instance_guid: VCSy8DAKCFIQYaItpSGyXhOXIlk5A6NWduVVG1u3:canvas-lms
tool_consumer_instance_name: University of Hypothesis
url: https://example.com
user_id: 4fb9bb0872a17e7c617041a7b043be478560eef3
user_image: https://canvas.instructure.com/images/messages/avatar-50.png
oauth_signature: aJesRiDlJKhPNPgtT+tN/9jcKyc=
```

</details>

2. **Parameters from the launch URL** we generate when an assignment is created. We don't currently include any dates here, and that date may not be the most useful guide as it is always before the due date.

3. We could consult the **Canvas API** and get the due date for the assignment. This would add an extra possible Canvas API authorization step to any LTI launches that use it, unless there is a way that the LMS app install itself can be authorized to access the Canvas API on its own behalf, rather than on behalf of a particular user.
